"""Constant variables for PGVA module."""

MAXIMUM_OUTPUT_PRESSURE_MBAR = 450
MINIMUM_OUTPUT_PRESSURE_MBAR = -450

MAXIMUM_PRESSURE_CHAMBER_MBAR = 1000
MINIMUM_PRESSURE_CHAMBER_MBAR = 200

MAXIMUM_VACUUM_CHAMBER_MBAR = -200
MINIMUM_VACUUM_CHAMBER_MBAR = -900

PRESSURE_CHAMBER_CONVERSION_FACTOR = 1 / 0.5543
VACUUM_CHAMBER_CONVERSION_FACTOR = 1 / -0.277
